# Generated by Django 5.2.17 on 2026-09-07 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0017_proforma_extra_tubing_metres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_live_default_item_per_subfamily_brand',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_live_item_identity',
        ),
        migrations.AddField(
            model_name='item',
            name='max_indoor_ports',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_lines', to='proformas.proformaline'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='proformas.subfamily'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True), ('kind', 'indoor')), fields=('sub_family', 'brand'), name='uniq_live_default_indoor_per_design_brand'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True), ('kind', 'outdoor')), fields=('brand', 'max_indoor_ports'), name='uniq_live_default_outdoor_per_brand_ports'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kind', 'indoor')), fields=('sub_family', 'brand', 'power'), name='uniq_live_indoor_identity'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kind', 'outdoor')), fields=('brand', 'power', 'max_indoor_ports'), name='uniq_live_outdoor_identity'),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='indoor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outdoor_matches', to='proformas.item'),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='outdoor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indoor_matches', to='proformas.item'),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itemmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('outdoor', 'indoor'), name='uniq_live_item_match'),
        ),
        migrations.AddConstraint(
            model_name='itemmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('indoor',), name='uniq_live_default_match_per_indoor'),
        ),
    ]
