# Generated by Django 5.2.17 on 2026-09-08 06:15

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

VOLUME_BANDS = {
    9000: (Decimal("0"), Decimal("20")),
    12000: (Decimal("21"), Decimal("35")),
    18000: (Decimal("36"), Decimal("50")),
}


def seed_power_volume_bands(apps, schema_editor):
    Power = apps.get_model("proformas", "Power")
    for amount, (vol_from, vol_to) in VOLUME_BANDS.items():
        Power.objects.filter(power=amount, unit="BTU").update(
            volume_from_m3=vol_from,
            volume_to_m3=vol_to,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("proformas", "0020_proforma_override_checks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="max_volume_m3",
        ),
        migrations.AddField(
            model_name="power",
            name="default_indoor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="powers_as_volume_default",
                to="proformas.item",
            ),
        ),
        migrations.AddField(
            model_name="power",
            name="volume_from_m3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="power",
            name="volume_to_m3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.RunPython(seed_power_volume_bands, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="power",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("volume_from_m3__isnull", True),
                        ("volume_to_m3__isnull", True),
                    ),
                    models.Q(
                        ("volume_from_m3__isnull", False),
                        ("volume_to_m3__isnull", False),
                        ("volume_from_m3__gte", 0),
                        ("volume_from_m3__lte", models.F("volume_to_m3")),
                    ),
                    _connector="OR",
                ),
                name="power_volume_band_valid",
            ),
        ),
    ]
